name: Create Jar Release

on:
  push:
    branches:
      - 1.19.2-release

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Get Mod Version
        run: |
          MOD_VERSION=$(grep '^version' build.gradle | awk '{print $3}' | tr -d "'")
          echo "mod_version=${MOD_VERSION}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle Build
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: LICENSE.txt
